package com.mds.decisionsupport.model;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class PatientImpl extends com.ibm.adtech.jastor.ThingImpl implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.math.BigInteger adress;
    
    @org.kie.api.definition.type.Position(value = 1)
    private com.hp.hpl.jena.datatypes.xsd.XSDDateTime birthDate;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String email;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String firstName;
    
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String lastName;
    
    @org.kie.api.definition.type.Position(value = 5)
    private java.util.ArrayList<com.mds.decisionsupport.model.MedicalRecord> medicalRecordOfPatient;
    
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.String phoneNumber;

    public PatientImpl() {
    }

    public PatientImpl(java.math.BigInteger adress, com.hp.hpl.jena.datatypes.xsd.XSDDateTime birthDate, java.lang.String email, java.lang.String firstName, java.lang.String lastName, java.util.ArrayList<com.mds.decisionsupport.model.MedicalRecord> medicalRecordOfPatient, java.lang.String phoneNumber) {
        this.adress = adress;
        this.birthDate = birthDate;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.medicalRecordOfPatient = medicalRecordOfPatient;
        this.phoneNumber = phoneNumber;
    }


    
    public java.math.BigInteger getAdress() {
        return this.adress;
    }

    public void setAdress(  java.math.BigInteger adress ) {
        this.adress = adress;
    }
    
    public com.hp.hpl.jena.datatypes.xsd.XSDDateTime getBirthDate() {
        return this.birthDate;
    }

    public void setBirthDate(  com.hp.hpl.jena.datatypes.xsd.XSDDateTime birthDate ) {
        this.birthDate = birthDate;
    }
    
    public java.lang.String getEmail() {
        return this.email;
    }

    public void setEmail(  java.lang.String email ) {
        this.email = email;
    }
    
    public java.lang.String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(  java.lang.String firstName ) {
        this.firstName = firstName;
    }
    
    public java.lang.String getLastName() {
        return this.lastName;
    }

    public void setLastName(  java.lang.String lastName ) {
        this.lastName = lastName;
    }
    
    public java.util.ArrayList<com.mds.decisionsupport.model.MedicalRecord> getMedicalRecordOfPatient() {
        return this.medicalRecordOfPatient;
    }

    public void setMedicalRecordOfPatient(  java.util.ArrayList<com.mds.decisionsupport.model.MedicalRecord> medicalRecordOfPatient ) {
        this.medicalRecordOfPatient = medicalRecordOfPatient;
    }
    
    public java.lang.String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(  java.lang.String phoneNumber ) {
        this.phoneNumber = phoneNumber;
    }
}